php artisan make:migration create_acc_years
php artisan make:migration create_assign_elements
php artisan make:migration create_brands
php artisan make:migration create_categories
php artisan make:migration create_elements
php artisan make:migration create_element_values
php artisan make:migration create_menus
php artisan make:migration create_plans
php artisan make:migration create_products
php artisan make:migration create_product_attributes
php artisan make:migration create_product_specifications
php artisan make:migration create_role_menus
php artisan make:migration create_send_approvals
php artisan make:migration create_sub_categories
php artisan make:migration create_sub_menus